name: Helm template action
description: Template Kubernetes resources using Helm

inputs:
  namespace:
    description: The namespace to use.
    required: true
  chart-dir:
    description: The location of the helm chart.
    required: false
    default: infra/helm/REPO_NAME

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - uses: azure/setup-helm@v1
    with:
      version: '3.9.0'
  - name: Get chart directory
    id: chart-dir
    env:
      CHART_DIR: ${{ inputs.chart-dir }}
      REPO: ${{ github.repository }}
    shell: bash
    run: |
      if [ "$CHART_DIR" != '' ]; then
        echo "::set-output name=dir::$CHART_DIR"
      else
        echo "::set-output name=dir::./infra/helm/${REPO/*\//}"
      fi
  - name: Helm template
    shell: bash
    run: helm template ${{ steps.chart-dir.outputs.dir }} --namespace ${{ inputs.namespace }} --output-dir ./manifests
  - name: Upload manifests
    uses: actions/upload-artifact@v3
    with:
      name: manifests
      path: ./manifests/
