name: Helm template action
description: Template Kubernetes resources using Helm

inputs:
  chart-dir:
    description: The location of the helm chart.
    required: false
  ecr-account-id:
    description: The AWS account ID for the ECR registry.
    required: false
  ecr-region:
    description: The region for the ECR registry.
    required: false
  ecr-role-arn:
    description: The role to assume for ECR authentication.
    required: false
  namespace:
    description: The namespace to use.
    required: true
  set-values:
    description: A comma-separated list of string values to set during templating via --set.
    required: false

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - uses: azure/setup-helm@v1
    with:
      version: '3.9.0'
  - name: Get chart directory
    id: chart-dir
    env:
      CHART_DIR: ${{ inputs.chart-dir }}
      REPO: ${{ github.repository }}
    shell: bash
    run: |
      if [ "$CHART_DIR" != '' ]; then
        echo "::set-output name=dir::$CHART_DIR"
      else
        echo "::set-output name=dir::./infra/helm/${REPO/*\//}"
      fi
  - name: Assume AWS role
    if: inputs.ecr-account-id != ''
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-region: ${{ inputs.ecr-region }}
      role-to-assume: ${{ inputs.ecr-role-arn }}
  - name: Authenticate Helm with ECR
    if: inputs.ecr-account-id != ''
    shell: bash
    run: |
      aws ecr get-login-password \
           --region ${{ inputs.ecr-region }} | helm registry login \
           --username AWS \
           --password-stdin ${{ inputs.ecr-account-id }}.dkr.ecr.${{ inputs.ecr-region }}.amazonaws.com
  - name: Fetch Helm dependencies
    shell: bash
    run: helm dep build ${{ steps.chart-dir.outputs.dir }}
  - name: Helm template
    shell: bash
    run: |
      args=(
        "${{ steps.chart-dir.outputs.dir }}"
        "--namespace" "${{ inputs.namespace }}"
        "--output-dir" "./manifests"
      )
      if [ ${{ inputs.set-values != '' ]; then
        args+=("--set" "${{ inputs.set-values }}")
      fi
      echo "Running helm template ${args[@]}..."
      helm template "${args[@]}"
  - name: Upload manifests
    uses: actions/upload-artifact@v3
    with:
      name: manifests
      path: ./manifests/
