name: ECR build and push action
description: Builds and pushes Docker images to ECR
branding:
  icon: anchor

inputs:
  codeartifact-domain:
    description: The Codeartifact domain.
    required: false
  codeartifact-domain-owner:
    description: The Codeartifact domain owner.
    required: false
  codeartifact-namespace:
    description: The Codeartifact namespace.
    required: false
  codeartifact-region:
    description: The region to use for Codeartifact.
    required: false
  codeartifact-repository:
    description: The Codeartifact repository.
    required: false
  codeartifact-role-arn:
    description: A role to assume for authenticating with Codeartifact.
    required: false
  ecr-lifecycle-policy:
    description: JSON lifecycle policy to apply to the ECR repo.
    required: false
  ecr-region:
    description: The region to use for ECR.
    required: true
  ecr-repo-name:
    description: The ECR repo name to use. If none is given, it defaults to "app/<github-repo-name>".
    required: false
  ecr-repo-policy:
    description: JSON policy to apply to the ECR repo.
    required: false
  ecr-role-arn:
    description: A role to assume for pulling packages from Codeartifact and publishing to ECR.
    required: true
  path:
    description: The path to the Dockerfile.
    required: false
    default: .

outputs:
  ecr-repo-name:
    description: The ECR repo name that was created.
    value: ${{ steps.ecr-repo-name.outputs.repo-name }}

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2
  - name: Assume ECR role
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-region: ${{ inputs.ecr-region }}
      role-to-assume: ${{ inputs.ecr-role-arn }}
  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1
  - name: Get ECR repo name
    id: ecr-repo-name
    env:
      DOCKERFILE_PATH: ${{ inputs.path }}
      REPO: ${{ github.repository }}
      REPO_NAME: ${{ inputs.ecr-repo-name }}
    shell: bash
    run: |
      if [[ ! $DOCKERFILE_PATH == '.' ]]; then
        suffix="-$(basename $DOCKERFILE_PATH)"
        suffix="${suffix//\./}"
      fi
      if [[ $REPO_NAME != '' ]]; then
        echo "::set-output name=repo-name::$REPO_NAME"
      else
        echo "::set-output name=repo-name::app/${REPO/*\//}$suffix"
      fi
  - name: Create ECR repo
    uses: byerobot/create-ecr-repository-action@v1
    id: create-ecr-repo
    with:
      repository: ${{ steps.ecr-repo-name.outputs.repo-name }}
      lifecycle-policy: ${{ inputs.ecr-lifecycle-policy }}
      repository-policy: ${{ inputs.ecr-repo-policy }}
  - name: Assume ECR role
    if: inputs.codeartifact-role-arn != ''
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-region: ${{ inputs.codeartifact-region }}
      role-to-assume: ${{ inputs.codeartifact-role-arn }}
  - name: Authenticate with CodeArtifact
    if: inputs.codeartifact-repository != ''
    shell: bash
    run: |
      aws codeartifact login \
        --tool npm \
        --domain ${{ inputs.codeartifact-domain }} \
        --domain-owner ${{ inputs.codeartifact-domain-owner }} \
        --namespace ${{ inputs.codeartifact-namespace }} \
        --repository ${{ inputs.codeartifact-repository }}
  - name: Check for existing image
    id: check-existing-image
    shell: bash
    run: |
      tags=$(aws ecr list-images \
        --repository-name ${{ steps.ecr-repo-name.outputs.repo-name }} \
        --query "imageIds[?imageTag=='${{ github.sha }}'].imageTag" \
        --output text)
      if [[ $tags != '' ]]; then
        echo "::set-output name=skip-build-push::true"
      else
        echo "::set-output name=skip-build-push::false"
      fi
  - name: Build and push
    if: ${{ ! steps.check-existing-image.outputs.skip-build-push }}
    uses: docker/build-push-action@v3
    with:
      context: ${{ inputs.path }}
      push: true
      tags: ${{ steps.create-ecr-repo.outputs.repository-uri }}:${{ github.sha }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
      secret-files: |
        "npmrc=/home/runner/.npmrc"
