name: EKS deploy action
description: Deploys or destroys Kubernetes resources in an EKS cluster

inputs:
  cluster:
    description: The name of the EKS cluster to deploy into.
    required: true
  environment:
    description: The environment to deploy into, i.e. "production".
    required: true
  namespace:
    description: The Kubernetes namespace to deploy into.
    required: true
  region:
    description: The AWS region to deploy into.
    required: true
  role_arn:
    description: An AWS role ARN that will be assumed for CDK operations.
    required: true
  task:
    description: The task to perform, i.e. "deploy" or "destroy".
    required: true
  twingate-service-key:
    description: A Twingate service key that will be used to connect to Twingate.
    required: false

runs:
  using: "composite"
  steps:
  - name: Download manifests
    uses: actions/download-artifact@v3
    with:
      name: manifests
  - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - name: Assume AWS role
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-region: ${{ inputs.region }}
      role-to-assume: ${{ inputs.role_arn }}
  - name: Authenticate with EKS cluster
    shell: bash
    run: |
      aws eks update-kubeconfig \
        --name ${{ inputs.cluster }} \
        --region ${{ inputs.region }}
  - name: Connect to Twingate
    uses: docker://twingate/connector:latest
    if: inputs.twingate-service-key != ''
    with:
      service-key: ${{ inputs.twingate-service-key }}
  - name: EKS ${{ inputs.task }}
    run: eks-deploy.sh
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      NAMESPACE: ${{ inputs.namespace }}
      TASK: ${{ inputs.task }}
    shell: bash
