name: Helm template action
description: Template Kubernetes resources using Helm
branding:
  icon: package

inputs:
  ecr-account-id:
    description: The AWS account ID for the ECR registry.
    required: false
  ecr-region:
    description: The region for the ECR registry.
    required: false
  ecr-role-arn:
    description: The role to assume for ECR authentication.
    required: false
  path:
    description: The path to the Chart.yaml.
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - uses: azure/setup-helm@v1
    with:
      version: '3.9.0'
  - name: Get chart name
    id: chart-name
    env:
      CHART_PATH: ${{ inputs.path }}
    shell: bash
    run: echo "::set-output name=name::$(basename $CHART_PATH)"
  - name: Assume AWS role
    if: inputs.ecr-account-id != ''
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-region: ${{ inputs.ecr-region }}
      role-to-assume: ${{ inputs.ecr-role-arn }}
  - name: Authenticate Helm with ECR
    if: inputs.ecr-account-id != ''
    shell: bash
    run: |
      aws ecr get-login-password \
           --region ${{ inputs.ecr-region }} | helm registry login \
           --username AWS \
           --password-stdin ${{ inputs.ecr-account-id }}.dkr.ecr.${{ inputs.ecr-region }}.amazonaws.com
  - name: Fetch Helm dependencies
    shell: bash
    run: helm dep build ${{ inputs.path }}
  - name: Helm package
    shell: bash
    run: |
      echo "Running helm package..."
      helm package "${{ inputs.path }}"
      mv ${{ steps.chart-name.outputs.name }}-*.tgz ${{ steps.chart-name.outputs.name }}.tgz
  - name: Upload package
    uses: actions/upload-artifact@v3
    with:
      if-no-files-found: error
      name: helm-package-${{ steps.chart-name.outputs.name }}
      path: ${{ steps.chart-name.outputs.name }}.tgz
