on:
  workflow_call:
    inputs:
      codeartifact_domain:
        required: false
        type: string
      codeartifact_domain_owner:
        required: false
        type: string
      codeartifact_namespace:
        required: false
        type: string
      codeartifact_repository:
        required: false
        type: string
      deployment_id:
        required: false
        type: number
      environment:
        required: true
        type: string
      env_vars:
        required: false
        type: string
      region:
        required: true
        type: string
      role_arn:
        required: true
        type: string
      stacks:
        required: false
        type: string
      task:
        required: true
        type: string

jobs:
  cdk-deploy:
    concurrency: ${{ inputs.environment }}
    environment: ${{ inputs.deployment_id == '' && inputs.environment || null }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f yarn.lock ]; then
            echo '::set-output name=cache-type::yarn'
            echo '::set-output name=dependency-command::yarn'
          else
            echo '::set-output name=cache-type::npm'
            echo '::set-output name=dependency-command::"npm ci"'
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: ${{ steps.detect-package-manager.outputs.cache-type }}
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ inputs.role_arn }}
      - name: Authenticate with CodeArtifact
        if: inputs.codeartifact_repository != ''
        run: |
          aws codeartifact login \
            --tool npm \
            --domain ${{ inputs.codeartifact_domain }} \
            --domain-owner ${{ inputs.codeartifact_domain_owner }} \
            --namespace ${{ inputs.codeartifact_namespace }} \
            --repository ${{ inputs.codeartifact_repository }}
      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.dependency-command }}
      - name: Run CDK command
        id: cdk
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          ENV_VARS: ${{ inputs.env_vars }}
          STACKS: ${{ inputs.stacks }}
          TASK: ${{ inputs.task }}
        run: |
          set -ueo pipefail
          if [ "$ENV_VARS" != "" ]; then
            IFS=','
            read -r -a vars <<< "$ENV_VARS"
            for val in "${vars[@]}"; do
              printf "%s\n" "$val"
              export "$val"
            done
          fi
          if [ "$STACKS" != "" ]; then
            stack_arg=$STACKS
          else
            stack_arg="--all"
          fi
          if [ "$TASK" == "deploy" ]; then
            echo "Running cdk deploy..."
            ./node_modules/.bin/cdk deploy --progress events --require-approval never --outputs-file cdk.out.json $stack_arg
            url=$(jq -r '.[].url' cdk.out.json)
            if [ "$url" != "null" ]; then
              echo "::set-output name=url::$url"
            fi
          elif [ "$TASK" == "destroy" ]; then
            if [[ "$ENVIRONMENT" =~ ^prod ]]; then
              echo "ERROR! Cannot destroy a production environment!!"
              exit 1
            else
              echo "Running cdk destroy..."
              ./node_modules/.bin/cdk destroy --progress events --force $stack_arg
            fi
          else
            echo "ERROR! Unrecognized action $TASK."
          fi
      - name: Upload outputs artifact
        uses: actions/upload-artifact@v3
        if: inputs.task == 'deploy'
        with:
          name: cdk.out.json
          path: cdk.out.json
      - name: Update deployment status (deploy)
        if: always() && inputs.task == 'deploy' && inputs.deployment_id != ''
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: ${{ steps.cdk.outputs.url }}
          state: ${{ job.status }}
          deployment-id: ${{ inputs.deployment_id }}
      - name: Update deployment status (destroy)
        uses: strumwolf/delete-deployment-environment@v2
        if: always() && inputs.task == 'destroy'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ inputs.environment }}
          onlyRemoveDeployments: true
