name: Deployment handler

on:
  workflow_call:
    inputs:
      cdk-role-arn:
        required: false
        type: string
      codeartifact-domain:
        required: false
        type: string
      codeartifact-domain-owner:
        required: false
        type: string
      codeartifact-namespace:
        required: false
        type: string
      codeartifact-region:
        required: false
        type: string
      codeartifact-repository:
        required: false
        type: string
      codeartifact-role-arn:
        required: false
        type: string
      cluster:
        required: false
        type: string
      deployment-id:
        required: false
        type: string
      deployment-target-name:
        required: true
        type: string
      ecr-account-id:
        required: false
        type: string
      ecr-region:
        required: false
        type: string
      ecr-role-arn:
        required: false
        type: string
      eks-role-arn:
        required: false
        type: string
      environment:
        required: true
        type: string
      extra-helm-values:
        required: false
        type: string
      namespace:
        required: true
        type: string
      region:
        required: true
        type: string
      stacks:
        required: false
        type: string
      task:
        required: true
        type: string
    secrets:
      twingate-service-key:
        required: false

jobs:
  detect-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Detect files
      id: detect-files
      run: |
        cdk_files=$(find . -not -path '*/.*' -name cdk.json -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')
        helm_files=$(find . -not -path '*/.*' -name Chart.yaml -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')
        
        echo "Found CDK files: $cdk_files"
        echo "Found Helm files: $helm_files"
        
        echo "::set-output name=cdk::$cdk_files"
        echo "::set-output name=helm::$helm_files"
    outputs:
      cdk: ${{ steps.detect-files.outputs.cdk }}
      helm: ${{ steps.detect-files.outputs.helm }}

  cdk-deploy:
    concurrency: cdk-${{ inputs.environment }}
    if: needs.detect-files.outputs.cdk != '[]'
    needs: detect-files
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ fromJSON(needs.detect-files.outputs.cdk) }}
    steps:
    - uses: byerobot/actions/cdk-deploy@helm
      id: cdk-deploy
      with:
        codeartifact-domain: ${{ inputs.codeartifact-domain }}
        codeartifact-domain-owner: ${{ inputs.codeartifact-domain-owner }}
        codeartifact-namespace: ${{ inputs.codeartifact-namespace }}
        codeartifact-region: ${{ inputs.codeartifact-region }}
        codeartifact-repository: ${{ inputs.codeartifact-repository }}
        codeartifact-role-arn: ${{ inputs.codeartifact-role-arn }}
        env-vars: ACCOUNT_NAME=${{ inputs.deployment-target-name }},NAMESPACE=${{ inputs.namespace }}
        environment: ${{ inputs.environment }}
        cdk-region: ${{ inputs.region }}
        cdk-role-arn: ${{ inputs.cdk-role-arn }}
        path: ${{ matrix.path }}
        task: ${{ inputs.task }}
    outputs:
      url: ${{ steps.cdk-deploy.outputs.url }}

  helm-package:
    if: needs.detect-files.outputs.helm != '[]' && inputs.task == 'deploy'
    needs: detect-files
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ fromJSON(needs.detect-files.outputs.helm) }}
    steps:
    - uses: byerobot/actions/helm-package@helm
      with:
        ecr-account-id: ${{ inputs.ecr-account-id }}
        ecr-region: ${{ inputs.ecr-region }}
        ecr-role-arn: ${{ inputs.ecr-role-arn }}
        path: ${{ matrix.path }}

  eks-helm-deploy:
    # We have to use the ugly conditional below because we want this step to run on destroy,
    # even though the helm-package step gets skipped.
    if: |
      always() && 
      needs.detect-files.outputs.helm != '[]' &&
      (needs.helm-package.result == 'success' || needs.helm-package.result == 'skipped')
    concurrency: eks-helm-${{ inputs.environment }}
    needs:
    - detect-files
    - helm-package
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ fromJSON(needs.detect-files.outputs.helm) }}
    steps:
    - uses: byerobot/actions/eks-helm-deploy@helm
      with:
        cluster: ${{ inputs.cluster }}
        environment: ${{ inputs.deployment-target-name }}
        extra-values: ${{ inputs.extra-helm-values }}
        namespace: ${{ inputs.namespace }}
        path: ${{ matrix.path }}
        region: ${{ inputs.region }}
        role-arn: ${{ inputs.eks-role-arn }}
        task: ${{ inputs.task }}
        twingate-service-key: ${{ secrets.twingate-service-key }}

  update-deployment:
    needs:
    - cdk-deploy
    - eks-helm-deploy
    if: always()
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
    - id: get-state
      run: |
        if [[ ${{ needs.cdk-deploy.result }} == 'skipped' ]] || [[ ${{ needs.cdk-deploy.result }} == 'success' ]]; then
          if [[ ${{ needs.eks-helm-deploy.result }} == 'skipped' ]] || [[ ${{ needs.eks-helm-deploy.result }} == 'success' ]]; then
            echo "::set-output name=state::success"
            exit 0
          fi
        fi
        echo "::set-output name=state::failure"
    - name: Update deployment status (deploy)
      if: inputs.task == 'deploy' && inputs.deployment-id != ''
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment-url: ${{ needs.cdk-deploy.outputs.url }}
        state: ${{ steps.get-state.outputs.state }}
        deployment-id: ${{ inputs.deployment-id }}
    - name: Update deployment status (destroy)
      uses: strumwolf/delete-deployment-environment@v2
      if: inputs.task == 'destroy'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: ${{ inputs.environment }}
        onlyRemoveDeployments: true
    # TODO: Send notification on failed destroys?
