on: deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ github.event.deployment.payload.region }}
          role-to-assume: ${{ github.event.deployment.payload.role_arn }}
      - name: Install dependencies
        run: yarn
      - name: CDK deploy
        id: cdk-deploy
        env:
          ACTION: ${{ github.event.deployment.task }}
          ENVIRONMENT: ${{ github.event.deployment.environment }}
          NAMESPACE: ${{ github.event.deployment.payload.namespace }}
        run:
          if [ $ACTION == "deploy" ]; then
            echo "Running cdk deploy..."
            ./node_modules/.bin/cdk deploy --progress events --require-approval never --outputs-file cdk.out.json
            echo "::set-output name=url::$(jq -r '.[].url' cdk.out.json)"
          elif [ $ACTION == "destroy" ]; then
            if [ $ENVIRONMENT =~ ^prod ]; then
              echo "ERROR! Cannot destroy a production environment!!"
              exit 1
            else
              echo "Running cdk destroy..."
              ./node_modules/.bin/cdk destroy --progress events --force
            fi
          fi
      - name: Update deployment status
        uses: bobheadxi/deployments@v1.2.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          step: finish
          status: ${{ job.status }}
          env: ${{ github.event.deployment.environment }}
          env_url: ${{ steps.cdk-deploy.outputs.url }}
          deployment_id: ${{ github.event.deployment.id }}
