on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      role_arn:
        required: true
        type: string

jobs:
  ecr-build-push:
    needs: deploy
    name: Build and push docker image to ECR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Assume AWS role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.role_arn }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Get ECR repo name
      id: ecr-repo-name
      env:
        REPO: ${{ github.repository }}
      run: echo "::set-output name=repo-name::${REPO/*\//}"
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ steps.ecr-repo-name.outputs.repo-name }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
