on:
  workflow_call:
    inputs:
      codeartifact_domain:
        required: false
        type: string
      codeartifact_domain_owner:
        required: false
        type: string
      codeartifact_namespace:
        required: false
        type: string
      codeartifact_repository:
        required: false
        type: string
      region:
        required: true
        type: string
      role_arn:
        required: true
        type: string

jobs:
  ecr-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Assume AWS role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.role_arn }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Get ECR repo name
      id: ecr-repo-name
      env:
        REPO: ${{ github.repository }}
      run: echo "::set-output name=repo-name::${REPO/*\//}"
    - name: Create ECR repo
      uses: int128/create-ecr-repository-action@v1
      id: create-ecr-repo
      with:
        repository: ${{ steps.ecr-repo-name.outputs.repo-name }}
    - name: Authenticate with CodeArtifact
      if: inputs.codeartifact_repository != ''
      run: |
        aws codeartifact login \
          --tool npm \
          --domain ${{ inputs.codeartifact_domain }} \
          --domain-owner ${{ inputs.codeartifact_domain_owner }} \
          --namespace ${{ inputs.codeartifact_namespace }} \
          --repository ${{ inputs.codeartifact_repository }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.create-ecr-repo.outputs.repository-uri }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        secret-files: |
          "npmrc=./.npmrc"
